import { useEffect, useMemo, useState } from 'react';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Sparkles, Copy, Send, RefreshCw, Edit3, Check } from 'lucide-react';
import { Input } from '../components/ui/Input';
import { api, Application } from '../lib/api';

type Draft = {
  startup: string;
  role?: string;
  subject: string;
  body: string;
  ai?: boolean;
};

const emptyDraft: Draft = {
  startup: '',
  role: '',
  subject: 'Select a startup in Discover to generate a backend draft',
  body: 'Email drafts are generated by POST /api/apply and saved with POST /api/mark-applied.',
};

export default function EmailDrafts() {
  const [applications, setApplications] = useState<Application[]>([]);
  const [activeDraft, setActiveDraft] = useState<Draft>(emptyDraft);
  const [tone, setTone] = useState('Professional');
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [body, setBody] = useState(emptyDraft.body);
  const [subject, setSubject] = useState(emptyDraft.subject);
  const [message, setMessage] = useState('');

  useEffect(() => {
    const storedDraft = sessionStorage.getItem('ff-active-draft');
    if (storedDraft) {
      const parsed = JSON.parse(storedDraft) as Draft;
      setActiveDraft(parsed);
      setSubject(parsed.subject);
      setBody(parsed.body);
    }

    api.getApplications()
      .then((result) => setApplications(result.applications))
      .catch((err) => setMessage(err instanceof Error ? err.message : 'Could not load applications'));
  }, []);

  const drafts = useMemo(() => {
    const saved = applications.map((app, index) => ({
      id: app.id || String(index),
      startup: app.startup_name || app.company || 'Startup',
      role: app.profile_used || 'Role',
      subject: app.email_subject || `Application for ${app.startup_name}`,
      body: app.notes || '',
    }));
    return activeDraft.startup ? [{ id: 'active', ...activeDraft }, ...saved] : saved;
  }, [applications, activeDraft]);

  const handleRegenerate = async () => {
    if (!activeDraft.startup) return;
    setIsRegenerating(true);
    try {
      const draft = await api.draftEmail(activeDraft.startup);
      setActiveDraft({ ...activeDraft, ...draft });
      setSubject(draft.subject);
      setBody(draft.body);
      sessionStorage.setItem('ff-active-draft', JSON.stringify({ ...activeDraft, ...draft }));
    } catch (err) {
      setMessage(err instanceof Error ? err.message : 'Could not regenerate email');
    } finally {
      setIsRegenerating(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(`Subject: ${subject}\n\n${body}`);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleMarkApplied = async () => {
    if (!activeDraft.startup) return;
    await api.markApplied(activeDraft.startup, subject);
    const result = await api.getApplications();
    setApplications(result.applications);
    setMessage('Application saved to backend.');
  };

  return (
    <div className="h-[calc(100vh-8rem)] flex gap-6 pb-6">
      <div className="w-1/4 flex flex-col gap-4">
        <h2 className="font-display font-semibold text-lg text-white">Drafts</h2>
        <div className="space-y-2 overflow-y-auto pr-2 scrollbar-hide flex-1">
          {drafts.map(draft => (
            <Card
              key={draft.id}
              className={`p-4 cursor-pointer transition-colors ${draft.startup === activeDraft.startup ? 'border-amber-500/50 bg-amber-500/5' : 'hover:bg-surface-200'}`}
              onClick={() => {
                setActiveDraft(draft);
                setSubject(draft.subject);
                setBody(draft.body || 'Saved application record from backend.');
              }}
            >
              <div className="flex justify-between items-start mb-1">
                <h3 className={`font-medium ${draft.startup === activeDraft.startup ? 'text-amber-400' : 'text-zinc-200'}`}>{draft.startup}</h3>
              </div>
              <p className="text-sm text-zinc-400">{draft.role}</p>
            </Card>
          ))}
          {!drafts.length && <p className="text-sm text-zinc-500">No backend drafts yet.</p>}
        </div>
      </div>

      <Card className="flex-1 flex flex-col overflow-hidden relative">
        <div className="absolute top-0 right-0 p-4 z-10">
          <div className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-purple-500/10 border border-purple-500/20 text-purple-400 text-xs font-medium backdrop-blur-md">
            <Sparkles size={14} /> {activeDraft.ai ? 'IBM Watsonx Granite' : 'Template Draft'}
          </div>
        </div>

        <div className="p-6 border-b border-white/5 bg-surface-100/80 backdrop-blur-sm">
          <div className="space-y-4">
            <div>
              <label className="text-xs font-medium text-zinc-500 uppercase tracking-wider mb-1 block">To</label>
              <Input value={activeDraft.startup ? `Hiring team at ${activeDraft.startup}` : 'No startup selected'} readOnly className="h-9 font-medium" />
            </div>
            <div>
              <label className="text-xs font-medium text-zinc-500 uppercase tracking-wider mb-1 block">Subject</label>
              <Input value={subject} onChange={(event) => setSubject(event.target.value)} readOnly={!isEditing} className="h-9 font-medium" />
            </div>
          </div>
        </div>

        <div className="flex-1 p-6 overflow-y-auto bg-surface-50 relative group">
          {isRegenerating && (
            <div className="absolute inset-0 bg-surface-50/80 backdrop-blur-sm z-10 flex items-center justify-center">
              <div className="flex flex-col items-center gap-3 text-purple-400 animate-pulse">
                <Sparkles size={32} />
                <span className="font-medium">Crafting the email through the backend...</span>
              </div>
            </div>
          )}

          <div className="max-w-2xl text-zinc-300 whitespace-pre-wrap font-sans leading-relaxed">
            <textarea
              className="w-full h-full min-h-[430px] bg-transparent resize-none focus:outline-none"
              value={body}
              readOnly={!isEditing}
              onChange={(event) => setBody(event.target.value)}
            />
          </div>
        </div>
      </Card>

      <div className="w-[300px] flex flex-col gap-6">
        <Card className="p-5 space-y-5">
          <div>
            <h3 className="text-sm font-medium text-zinc-400 mb-3">Tone Adjustments</h3>
            <div className="flex flex-wrap gap-2">
              {['Professional', 'Friendly', 'Bold', 'Direct'].map(t => (
                <button key={t} onClick={() => setTone(t)} className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${tone === t ? 'bg-purple-500 text-white shadow-[0_0_10px_rgba(139,92,246,0.3)]' : 'bg-surface-200 text-zinc-400 hover:text-white'}`}>
                  {t}
                </button>
              ))}
            </div>
          </div>

          <Button className="w-full bg-purple-600 hover:bg-purple-500 text-white gap-2 shadow-[0_0_15px_rgba(139,92,246,0.3)]" onClick={handleRegenerate} disabled={!activeDraft.startup || isRegenerating}>
            <RefreshCw size={16} className={isRegenerating ? 'animate-spin' : ''} /> Regenerate
          </Button>
        </Card>

        <Card className="p-5 flex flex-col gap-3">
          <Button variant="outline" className="w-full gap-2 justify-start" onClick={() => setIsEditing(!isEditing)}>
            <Edit3 size={16} /> {isEditing ? 'Save Changes' : 'Edit Manually'}
          </Button>

          <Button variant="outline" className="w-full gap-2 justify-start" onClick={handleCopy}>
            {copied ? <><Check size={16} className="text-emerald-500" /> Copied!</> : <><Copy size={16} /> Copy to Clipboard</>}
          </Button>

          <Button className="w-full gap-2 justify-start bg-blue-600 hover:bg-blue-500 text-white border-none shadow-[0_0_15px_rgba(37,99,235,0.3)]" onClick={handleMarkApplied} disabled={!activeDraft.startup}>
            <Send size={16} /> Mark Applied
          </Button>
        </Card>

        <Card className="p-5 flex-1">
          <h3 className="text-sm font-medium text-zinc-400 mb-3">Backend Status</h3>
          <p className="text-xs text-zinc-500">{message || `${applications.length} applications loaded from /api/applications.`}</p>
        </Card>
      </div>
    </div>
  );
}
